# Generated by Django 5.1.2 on 2024-10-15 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='creator',
            field=models.ForeignKey(default='starky', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
